[package]
name = "kulala-http"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/kulala_http.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"

[dev-dependencies]
tracing = "0.1.44"
